"""empty message

Revision ID: 1b00c66f3f48
Revises: 99461983bce2
Create Date: 2022-06-16 19:09:43.890340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b00c66f3f48'
down_revision = '99461983bce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'works_friday')
    op.drop_column('employees', 'works_monday')
    op.drop_column('employees', 'works_wednesday')
    op.drop_column('employees', 'works_saturday')
    op.drop_column('employees', 'works_thursday')
    op.drop_column('employees', 'works_tuesday')
    op.drop_column('employees', 'works_sunday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('works_sunday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('works_tuesday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('works_thursday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('works_saturday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('works_wednesday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('works_monday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('employees', sa.Column('works_friday', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
