"""empty message

Revision ID: ef3447fcc91e
Revises: 1b00c66f3f48
Create Date: 2022-06-17 15:48:57.122269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3447fcc91e'
down_revision = '1b00c66f3f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('Monday', sa.String(), nullable=True),
    sa.Column('Tuesday', sa.String(), nullable=True),
    sa.Column('Wednesday', sa.String(), nullable=True),
    sa.Column('Thursday', sa.String(), nullable=True),
    sa.Column('Friday', sa.String(), nullable=True),
    sa.Column('Saturday', sa.String(), nullable=True),
    sa.Column('Sunday', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_schedules',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'schedule_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
