"""empty message

Revision ID: 99461983bce2
Revises: d3e107c13ada
Create Date: 2022-06-16 17:25:07.817313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99461983bce2'
down_revision = 'd3e107c13ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('works_friday', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('works_monday', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('works_saturday', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('works_sunday', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('works_thursday', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('works_tuesday', sa.Boolean(), nullable=True))
    op.add_column('employees', sa.Column('works_wednesday', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'works_wednesday')
    op.drop_column('employees', 'works_tuesday')
    op.drop_column('employees', 'works_thursday')
    op.drop_column('employees', 'works_sunday')
    op.drop_column('employees', 'works_saturday')
    op.drop_column('employees', 'works_monday')
    op.drop_column('employees', 'works_friday')
    # ### end Alembic commands ###
