"""empty message

Revision ID: 03fe49baa8ed
Revises: 91f36c06e8f9
Create Date: 2022-06-19 16:18:49.068737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fe49baa8ed'
down_revision = '91f36c06e8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('employees', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
