"""empty message

Revision ID: 5e8f49d64ed3
Revises: 03fe49baa8ed
Create Date: 2022-06-19 18:39:04.572107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8f49d64ed3'
down_revision = '03fe49baa8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('total_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'total_hours')
    # ### end Alembic commands ###
